### ISSUE TITLE
ASG Python 3.8 deprecated, update Lambda 

### ISSUE THREAD

**Issue by pimielowski** [PaloAltoNetworks/terraform-aws-swfw-modules#42]
### Is your feature request related to a problem?

<html>
<body>

Python 3.8 | python3.8 | Amazon Linux 2 | Oct 14, 2024
-- | -- | -- | --

</body>
</html>
Since AWS announces deprecation of the Python 3.8 it is recommended to update the codebase to Python 3.12+. 
In this issue, we can also add a feature to handle IPv6 creation of the ENI. 

### Describe the solution you'd like

Support higher version of the Python

**Comment by sebastianczech** [comment]
As module `asg` uses `pan-os-python` in version `1.11.0`, we cannot use `Python 3.12`, because there are still opened issues like https://github.com/PaloAltoNetworks/pan-os-python/issues/529. In this feature request Lambda is going to be updated to `Python 3.11`.

For IPv6 support I recommend to open separate feature request as it's different requirements.
